# Generated by Django 6.1.1 on 2026-10-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="api_keys",
        ),
        migrations.AddField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (one org has many keys). Null = unassigned legacy key.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_keys",
                to="api.organization",
            ),
        ),
    ]
