# Generated by Django 6.1.1 on 2026-10-02 05:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    api.models.NanoIDField(
                        default=api.models.generate_nanoid,
                        editable=False,
                        max_length=21,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Stocks",
                "db_table": "Stocks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    api.models.NanoIDField(
                        default=api.models.generate_nanoid,
                        editable=False,
                        max_length=21,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Warehouses",
                "db_table": "Warehouses",
                "managed": False,
            },
        ),
    ]
