# Generated by Django 6.1.1 on 2026-10-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_backfill_from_api"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="uniq_primary_category_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", True), ("role", "main")),
                fields=("product",),
                name="uniq_main_media_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", False), ("role", "main")),
                fields=("product", "channel"),
                name="uniq_main_media_product_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", True), ("role", "main")),
                fields=("variant",),
                name="uniq_main_media_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", False), ("role", "main")),
                fields=("variant", "channel"),
                name="uniq_main_media_variant_channel",
            ),
        ),
    ]
