# Generated by Django 6.1.1 on 2026-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productcategory_uniq_primary_category_per_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable key for feeds/URLs. Auto-filled from name.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
