# Generated by Django 6.1.1 on 2026-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="Stable key for feeds/URLs. Auto-filled from name.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
