# Generated by Django 6.1.1 on 2026-10-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_brand_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV")],
                        default="json",
                        max_length=4,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "only_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude products below 100% completeness for this scope.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeds",
                        to="catalog.channel",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeds",
                        to="catalog.locale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=7,
                    ),
                ),
                ("items", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path relative to FEEDS_ROOT; empty when the run failed.",
                        max_length=255,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="catalog.feed",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
