# Generated by Django 6.1.1 on 2026-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_feed_feedrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedrun",
            name="skipped",
            field=models.JSONField(
                default=list,
                help_text="SKUs excluded by only_complete (or undefined completeness).",
            ),
        ),
    ]
