# Generated by Django 6.1.1 on 2026-10-05 15:28
# (RunPython appended by hand: 0007 stored skipped as a flat SKU list;
#  that shape no longer validates, so convert legacy rows on upgrade.)

from django.db import migrations, models


def _wrap_legacy_skipped(apps, schema_editor):
    FeedRun = apps.get_model('catalog', 'FeedRun')
    for run in FeedRun.objects.all().only('id', 'skipped'):
        if isinstance(run.skipped, list):
            # Old rows predate reason grouping; only_complete was the sole
            # gate then, so 'incomplete' is the honest bucket.
            run.skipped = {'incomplete': list(run.skipped)}
            run.save(update_fields=['skipped'])


def _unwrap_legacy_skipped(apps, schema_editor):
    FeedRun = apps.get_model('catalog', 'FeedRun')
    for run in FeedRun.objects.all().only('id', 'skipped'):
        if isinstance(run.skipped, dict):
            flat = []
            for skus in run.skipped.values():
                flat.extend(skus)
            run.skipped = flat
            run.save(update_fields=['skipped'])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_feedrun_skipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="schedule_cron",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Crontab cadence (e.g. '0 6 * * *'); blank = manual builds only.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Approved for feeds. is_active = exists in PIM; is_published = may leave the building.",
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="last_shipped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent build that shipped this product.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First build that shipped this product (frozen; the Studio diff baseline).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Approved for feeds. is_active = exists in PIM; is_published = may leave the building.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="last_shipped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent build that shipped this product.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First build that shipped this product (frozen; the Studio diff baseline).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedrun",
            name="skipped",
            field=models.JSONField(
                default=dict,
                help_text="{reason: [skus]} excluded from this build (unpublished / incomplete / no_rule).",
            ),
        ),
        migrations.RunPython(_wrap_legacy_skipped, _unwrap_legacy_skipped),
    ]
