# Generated by Django 6.1.1 on 2026-10-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_historicalproductvariant_list_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedrun",
            name="report",
            field=models.JSONField(
                default=dict,
                help_text="Platform transform report (warnings/notes); {} for generic feeds.",
            ),
        ),
        migrations.AlterField(
            model_name="feedrun",
            name="skipped",
            field=models.JSONField(
                default=dict,
                help_text="{reason: [skus]} excluded from this build (unpublished / incomplete / no_rule / platform reasons).",
            ),
        ),
    ]
