# Generated by Django 6.1.1 on 2026-10-02 05:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    api.models.NanoIDField(
                        default=api.models.generate_nanoid,
                        editable=False,
                        max_length=21,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lead_time", models.IntegerField(help_text="Lead time in days")),
            ],
            options={
                "verbose_name_plural": "Product Suppliers",
                "db_table": "Product Suppliers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    api.models.NanoIDField(
                        default=api.models.generate_nanoid,
                        editable=False,
                        max_length=21,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Suppliers",
                "db_table": "Suppliers",
                "managed": False,
            },
        ),
    ]
